function request(actionType) {
  return {
    type: actionType,
  };
}

function success(actionType, response) {
  return {
    type: actionType,
    payload: response,
  };
}

function failure(actionType, error) {
  return {
    type: actionType,
    payload: error,
  };
}
const ADMIN_LOGIN = {
  ADMIN_LOGIN_REQUEST: "ADMIN_LOGIN_REQUEST",
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAILURE: "ADMIN_LOGIN_FAILURE",

  TWO_FA_CODE_REQUEST: "TWO_FA_CODE_REQUEST",
  TWO_FA_CODE_SUCCESS: "TWO_FA_CODE_SUCCESS",
  TWO_FA_CODE_FAILURE: "TWO_FA_CODE_FAILURE",
};

const CLIENT_FILTERED_LIST = {
  GET_ALL_COUNTRIES_REQUEST: "GET_ALL_COUNTRIES_REQUEST",
  GET_ALL_COUNTRIES_SUCCESS: "GET_ALL_COUNTRIES_SUCCESS",
  GET_ALL_COUNTRIES_FAILURE: "GET_ALL_COUNTRIES_FAILURE",
};
const ADMIN_PROFILE = {
  ADMIN_PROFILE_RESET: "ADMIN_PROFILE_RESET",
  ADMIN_PROFILE_REQUEST: "ADMIN_PROFILE_REQUEST",
  ADMIN_PROFILE_SUCCESS: "ADMIN_PROFILE_SUCCESS",
  ADMIN_PROFILE_FAILURE: "ADMIN_PROFILE_FAILURE",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",

  TWO_FACTOR_REQUEST: "TWO_FACTOR_REQUEST",
  TWO_FACTOR_SUCCESS: "TWO_FACTOR_SUCCESS",
  TWO_FACTOR_FAILURE: "TWO_FACTOR_FAILURE",

  SESSION_LOG_SAVE_REQUEST: "SESSION_LOG_SAVE_REQUEST",
  SESSION_LOG_SAVE_SUCCESS: "SESSION_LOG_SAVE_SUCCESS",
  SESSION_LOG_SAVE_FAILURE: "SESSION_LOG_SAVE_FAILURE",

  SESSION_LOG_SINGLE_DELETE_REQUEST: "SESSION_LOG_SINGLE_DELETE_REQUEST",
  SESSION_LOG_SINGLE_DELETE_SUCCESS: "SESSION_LOG_SINGLE_DELETE_SUCCESS",
  SESSION_LOG_SINGLE_DELETE_FAILURE: "SESSION_LOG_SINGLE_DELETE_FAILURE",

  SESSION_LOG_DELETE_ALL_REQUEST: "SESSION_LOG_DELETE_ALL_REQUEST",
  SESSION_LOG_DELETE_ALL_SUCCESS: "SESSION_LOG_DELETE_ALL_SUCCESS",
  SESSION_LOG_DELETE_ALL_FAILURE: "SESSION_LOG_DELETE_ALL_FAILURE",

  SESSION_LOG_LIST_REQUEST: "SESSION_LOG_LIST_REQUEST",
  SESSION_LOG_LIST_SUCCESS: "SESSION_LOG_LIST_SUCCESS",
  SESSION_LOG_LIST_FAILURE: "SESSION_LOG_LIST_FAILURE",

  SESSION_EXIST_REQUEST: "SESSION_EXIST_REQUEST",
  SESSION_EXIST_SUCCESS: "SESSION_EXIST_SUCCESS",
  SESSION_EXIST_FAILURE: "SESSION_EXIST_FAILURE",
};
const APPROVED_CERTIFICATES = {
  GET_APPROVED_CERTIFICATES_REQUEST: "GET_APPROVED_CERTIFICATES_REQUEST",
  GET_APPROVED_CERTIFICATES_SUCCESS: "GET_APPROVED_CERTIFICATES_SUCCESS",
  GET_APPROVED_CERTIFICATES_FAILURE: "GET_APPROVED_CERTIFICATES_FAILURE",

  GET_LIST_EXPORT_CSV_REQUEST: "GET_LIST_EXPORT_CSV_REQUEST",
  GET_LIST_EXPORT_CSV_SUCCESS: "GET_LIST_EXPORT_CSV_SUCCESS",
  GET_LIST_EXPORT_CSV_FAILURE: "GET_LIST_EXPORT_CSV_FAILURE",

  CLIENT_RESET_PASSWORD_REQUEST: "CLIENT_RESET_PASSWORD_REQUEST",
  CLIENT_RESET_PASSWORD_SUCCESS: "CLIENT_RESET_PASSWORD_SUCCESS",
  CLIENT_RESET_PASSWORD_FAILURE: "CLIENT_RESET_PASSWORD_FAILURE",

  GET_APPROVED_CERTIFICATES_SINGLE_REQUEST: "GET_APPROVED_CERTIFICATES_SINGLE_REQUEST",
  GET_APPROVED_CERTIFICATES_SINGLE_SUCCESS: "GET_APPROVED_CERTIFICATES_SINGLE_SUCCESS",
  GET_APPROVED_CERTIFICATES_SINGLE_FAILURE: "GET_APPROVED_CERTIFICATES_SINGLE_FAILURE",

  SEND_ORIGINAL_REQUEST: "SEND_ORIGINAL_REQUEST",
  SEND_ORIGINAL_SUCCESS: "SEND_ORIGINAL_SUCCESS",
  SEND_ORIGINAL_FAILURE: "SEND_ORIGINAL_FAILURE",

  SEND_UPDATE_REQUEST: "SEND_UPDATE_REQUEST",
  SEND_UPDATE_SUCCESS: "SEND_UPDATE_SUCCESS",
  SEND_UPDATE_FAILURE: "SEND_UPDATE_FAILURE",
}

const ADD_ADMIN = {
  CLIENT_FILTERED_LIST_REQUEST: "CLIENT_FILTERED_LIST_REQUEST",
  CLIENT_FILTERED_LIST_SUCCESS: "CLIENT_FILTERED_LIST_SUCCESS",
  CLIENT_FILTERED_LIST_FAILURE: "CLIENT_FILTERED_LIST_FAILURE",
  CLIENT_FILTERED_LIST_RESET: "CLIENT_FILTERED_LIST_RESET",

  GET_CLIENT_SINGLE_OR_LIST_REQUEST: "GET_CLIENT_SINGLE_OR_LIST_REQUEST",
  GET_CLIENT_SINGLE_OR_LIST_SUCCESS: "GET_CLIENT_SINGLE_OR_LIST_SUCCESS",
  GET_CLIENT_SINGLE_OR_LIST_FAILURE: "GET_CLIENT_SINGLE_OR_LIST_FAILURE",

  ADD_ADMIN_REQUEST: "ADD_ADMIN_REQUEST",
  ADD_ADMIN_SUCCESS: "ADD_ADMIN_SUCCESS",
  ADD_ADMIN_FAILURE: "ADD_ADMIN_FAILURE",

  DELETE_ADMIN_REQUEST: "DELETE_ADMIN_REQUEST",
  DELETE_ADMIN_SUCCESS: "DELETE_ADMIN_SUCCESS",
  DELETE_ADMIN_FAILURE: "DELETE_ADMIN_FAILURE",

  ADMIN_GET_ALL_OR_LIST_REQUEST: "ADMIN_GET_ALL_OR_LIST_REQUEST",
  ADMIN_GET_ALL_OR_LIST_SUCCESS: "ADMIN_GET_ALL_OR_LIST_SUCCESS",
  ADMIN_GET_ALL_OR_LIST_FAILURE: "ADMIN_GET_ALL_OR_LIST_FAILURE",

  CHANGE_ACTIVE_STATUS_REQUEST: "CHANGE_ACTIVE_STATUS_REQUEST",
  CHANGE_ACTIVE_STATUS_SUCCESS: "CHANGE_ACTIVE_STATUS_SUCCESS",
  CHANGE_ACTIVE_STATUS_FAILURE: "CHANGE_ACTIVE_STATUS_FAILURE",

  FILTER_TEST_REPORT_REQUEST: "FILTER_TEST_REPORT_REQUEST",
  FILTER_TEST_REPORT_SUCCESS: "FILTER_TEST_REPORT_SUCCESS",
  FILTER_TEST_REPORT_FAILURE: "FILTER_TEST_REPORT_FAILURE",

  TEST_REPORT_COUNT_REQUEST: "TEST_REPORT_COUNT_REQUEST",
  TEST_REPORT_COUNT_SUCCESS: "TEST_REPORT_COUNT_SUCCESS",
  TEST_REPORT_COUNT_FAILURE: "TEST_REPORT_COUNT_FAILURE",

  CHANGE_ACTIVE_BLOCKS_STATUS_REQUEST: "CHANGE_ACTIVE_BLOCKS_STATUS_REQUEST",
  CHANGE_ACTIVE_BLOCKS_STATUS_SUCCESS: "CHANGE_ACTIVE_BLOCKS_STATUS_SUCCESS",
  CHANGE_ACTIVE_BLOCKS_STATUS_FAILURE: "CHANGE_ACTIVE_BLOCKS_STATUS_FAILURE",
  SUBMIT_FOR_REVIEW_REQUEST: "SUBMIT_FOR_REVIEW_REQUEST",
  SUBMIT_FOR_REVIEW_SUCCESS: "SUBMIT_FOR_REVIEW_SUCCESS",
  SUBMIT_FOR_REVIEW_FAILURE: "SUBMIT_FOR_REVIEW_FAILURE",

  TAKE_DECISION_REQUEST: "TAKE_DECISION_REQUEST",
  TAKE_DECISION_SUCCESS: "TAKE_DECISION_SUCCESS",
  TAKE_DECISION_FAILURE: "TAKE_DECISION_FAILURE",

  REACTIVE_DEVICES_REQUEST: "REACTIVE_DEVICES_REQUEST",
  REACTIVE_DEVICES_SUCCESS: "REACTIVE_DEVICES_SUCCESS",
  REACTIVE_DEVICES_FAILURE: "REACTIVE_DEVICES_FAILURE",

};
//Esign

const REGISTRATION = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
}

const OPT = {
  OPT_REQUEST: "OPT_REQUEST",
  OPT_SUCCESS: "OPT_SUCCESS",
  OPT_FAILURE: "OPT_FAILURE",
}

const CLIENT_GET_PROFILE = {
  CLIENT_GET_PROFILE_REQUEST: "CLIENT_GET_PROFILE_REQUEST",
  CLIENT_GET_PROFILE_SUCCESS: "CLIENT_GET_PROFILE_SUCCESS",
  CLIENT_GET_PROFILE_FAILURE: "CLIENT_GET_PROFILE_FAILURE",
}
const CLIENT_USER = {
  CLIENT_MANAGE_PROFILE_REQUEST: "CLIENT_MANAGE_PROFILE_REQUEST",
  CLIENT_MANAGE_PROFILE_SUCCESS: "CLIENT_MANAGE_PROFILE_SUCCESS",
  CLIENT_MANAGE_PROFILE_FAILURE: "CLIENT_MANAGE_PROFILE_FAILURE",

  CLIENT_GET_PROFILE_REQUEST: "CLIENT_GET_PROFILE_REQUEST",
  CLIENT_GET_PROFILE_SUCCESS: "CLIENT_GET_PROFILE_SUCCESS",
  CLIENT_GET_PROFILE_FAILURE: "CLIENT_GET_PROFILE_FAILURE",
}
export {
  request,
  success,
  failure,
  ADMIN_LOGIN,
  CLIENT_FILTERED_LIST,
  ADD_ADMIN,
  ADMIN_PROFILE,
  APPROVED_CERTIFICATES,
  REGISTRATION,
  OPT,
  CLIENT_GET_PROFILE,
  CLIENT_USER
};
